version: '3.8'

services:
  sslsetup:
    container_name: sslsetup
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../server_data:/app/server_data
    environment:
      PORT: 3000

  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../server_data/acme:/var/www/certbot:ro
      - ../server_data/certbot_data:/etc/letsencrypt:ro
    depends_on:
      - sslsetup

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      # folder for the acme challenge files
      - ../server_data/acme:/var/www/certbot
      # folder for internal certbot data
      - ../server_data/certbot_data:/etc/letsencrypt
    depends_on:
      - nginx-proxy

    # set domain after -d {domain.tld}, and email after -m {email}
    # sleep {seconds} defines the refresh interval
    entrypoint: >
      /bin/sh -c "
      certbot certonly -m contact@harmoneyz.com -d harmoneyz.com \
      -n --agree-tos --webroot --webroot-path /var/www/certbot && \
      chmod -R 755 /etc/letsencrypt && \
      while :; do certbot renew; sleep 86400; done"
